# Configuration système WSL2
[boot]
systemd=true
command="mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc"

[automount]
enabled=true
options="metadata,uid=1000,gid=1000,umask=022,fmask=011"
mountFsTab=true
crossDistro=true

[network]
generateHosts=true
generateResolvConf=true

[interop]
enabled=true
appendWindowsPath=false

[user]
default=ubuntu
