#!/usr/bin/env python3
import json
from pathlib import Path

def fix_french_typography(text):
    """Applique les règles typographiques françaises."""
    # Espaces avant la ponctuation double
    for punct in [':', ';', '!', '?']:
        text = text.replace(f' {punct}', f' {punct}')
        text = text.replace(punct, f' {punct}')
    
    # Gestion des guillemets français
    # Sauvegarde des apostrophes
    text = text.replace("'", "###APOSTROPHE###")
    
    # Remplacement des guillemets droits
    text = text.replace('" ', ' » ')
    text = text.replace(' "', ' « ')
    text = text.replace('"', ' « ')
    
    # Restauration des apostrophes
    text = text.replace("###APOSTROPHE###", "'")
    
    # Nettoyage des espaces multiples
    text = ' '.join(text.split())
    
    # Correction des espaces autour des guillemets
    text = text.replace('«  ', '« ')
    text = text.replace('  »', ' »')
    text = text.replace(' »  ', ' » ')
    text = text.replace('  « ', ' « ')
    
    return text

def translate_tips():
    """Traduit le fichier tips.json en respectant les règles typographiques."""
    # Chemins des fichiers
    input_file = Path("localization/fr/data/strings/tips.json")
    output_file = Path("localization/fr/data/strings/tips.json.new")
    
    try:
        # Lecture du fichier JSON
        with open(input_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        # Traduction des conseils
        translations = {
            # Conseils de base
            "You can change the frequency of tips by adding a json object instead of a string, like so. For example, this tip has a frequency of 0 and will never show up. The default freq value is 1.": 
                "Vous pouvez modifier la fréquence d'apparition des conseils en utilisant un objet JSON plutôt qu'une simple chaîne de caractères. Par exemple, ce conseil a une fréquence de 0 et n'apparaîtra jamais. La fréquence par défaut est 1.",
            
            # Conseils sur les boucliers et le flux
            "Lower your shields to dissipate \"hard\" flux generated by taking shield damage.":
                "Désactivez vos boucliers pour dissiper le flux « dur » généré par les dégâts qu'ils subissent.",
            
            "Shields and weapons both generate flux, so lowering your shields to take some hits on hull and armor will increase your sustained firepower. This can be vital, especially for heavily armored ships.":
                "Les boucliers et les armes génèrent tous deux du flux. Désactiver vos boucliers pour encaisser des dégâts sur la coque et l'armure augmentera votre puissance de feu soutenue. Cela peut être vital, en particulier pour les vaisseaux lourdement blindés.",
            
            "Beam weapons hitting shields generate \"soft\" flux which can be dissipated without lowering shields.":
                "Les armes à faisceau touchant les boucliers génèrent du flux « mou » qui peut être dissipé sans désactiver les boucliers.",
            
            # Commandes et interface
            "Press TAB to bring up the command interface and give orders to your fleet.":
                "Appuyez sur TAB pour afficher l'interface de commandement et donner des ordres à votre flotte.",
            
            "Warning: assigning a ship to escort duty will limit its mobility. Use this order with caution.":
                "Attention : assigner un vaisseau en escorte limitera sa mobilité. Utilisez cet ordre avec précaution.",
            
            "If your shields take too much damage, the ship will overload and weapons and shields will be disabled for a few seconds.":
                "Si vos boucliers subissent trop de dégâts, le vaisseau sera en surcharge et les armes ainsi que les boucliers seront désactivés pendant quelques secondes.",
            
            "Long range missiles (LRMs) can hit targets from beyond visual range. Press Tab to open the command UI and target far-away ships by clicking on them and then selecting 'Set as Target'.":
                "Les missiles à longue portée peuvent toucher des cibles au-delà du champ de vision. Appuyez sur Tab pour ouvrir l'interface de commande et ciblez les vaisseaux éloignés en cliquant dessus puis en sélectionnant « Définir comme cible ».",
            
            "In combat, move the mouse around to pan the view. Press 'T' to anchor your view to your target, and press 'T' again to go back to the normal view.":
                "En combat, déplacez la souris pour faire défiler la vue. Appuyez sur « T » pour verrouiller la vue sur votre cible, et appuyez à nouveau sur « T » pour revenir à la vue normale.",
            
            "Press LMB to fire and RMB to use the shields. Use WASD to pilot the ship.":
                "Appuyez sur le bouton gauche de la souris pour tirer et sur le bouton droit pour utiliser les boucliers. Utilisez ZQSD pour piloter le vaisseau.",
            
            # Types de dégâts
            "Kinetic damage is good against shields, while high-explosive damage is good against armor.":
                "Les dégâts cinétiques sont efficaces contre les boucliers, tandis que les dégâts hautement explosifs sont efficaces contre l'armure.",
            
            "Fragmentation damage is poor against everything but exposed hull, but weapons dealing it tend to be very flux-efficient.":
                "Les dégâts de fragmentation sont peu efficaces contre tout sauf la coque exposée, mais les armes qui en infligent ont tendance à être très économes en flux.",
            
            "Energy weapons do equally well against both shields and armor, but aren't as good as more specialized damage types vs either.":
                "Les armes à énergie sont également efficaces contre les boucliers et l'armure, mais ne sont pas aussi performantes que les types de dégâts plus spécialisés contre l'un ou l'autre.",
            
            # Armes et missiles
            "A missile weapon slot is versatile - there are missiles to fulfill virtually every role - but missile launchers usually have very low ammo.":
                "Un emplacement d'arme à missiles est polyvalent - il existe des missiles pour pratiquement tous les rôles - mais les lance-missiles ont généralement très peu de munitions.",
            
            # Flux et vitesse
            "Firing weapons or using shields builds up flux. When the flux level is maxed out, you'll have to wait for it to go down before you can fire again.":
                "Tirer avec les armes ou utiliser les boucliers accumule du flux. Quand le niveau de flux est au maximum, vous devrez attendre qu'il redescende avant de pouvoir tirer à nouveau.",
            
            "Ships receive a boost to top speed when their flux level is zero and they're not generating any flux.":
                "Les vaisseaux reçoivent un bonus de vitesse maximale lorsque leur niveau de flux est à zéro et qu'ils n'en génèrent pas.",
            
            # Interface et raccourcis
            "When refitting a ship, Shift-click on a weapon slot to install the previously selected weapon without opening the weapon selection menu.":
                "Lors du réaménagement d'un vaisseau, maintenez Shift en cliquant sur un emplacement d'arme pour installer l'arme précédemment sélectionnée sans ouvrir le menu de sélection.",
            
            "When creating weapon groups for a ship, Shift-click to assign all weapons of the same type.":
                "Lors de la création de groupes d'armes pour un vaisseau, maintenez Shift en cliquant pour assigner toutes les armes du même type.",
            
            # Transporteurs et chasseurs
            "Press 'Z' to toggle between ordering a carrier's fighters to attack or pull back to the carrier.":
                "Appuyez sur « Z » pour alterner entre ordonner aux chasseurs d'un transporteur d'attaquer ou de se replier.",
            
            "Ordering fighters to regroup will make the carrier's replacement rate go down more slowly, and will make damaged wings try to shelter behind the carrier.":
                "Ordonner aux chasseurs de se regrouper ralentira la diminution du taux de remplacement du transporteur et les escadrilles endommagées tenteront de s'abriter derrière lui.",
            
            "When piloting a carrier, its fighters will escort a friendly ship if the carrier targets it, and will continue escorting it until recalled even if the target is cleared.":
                "En pilotant un transporteur, ses chasseurs escorteront un vaisseau allié si le transporteur le cible, et continueront l'escorte jusqu'à leur rappel, même si la cible est désélectionnée.",
            
            "Bombers have high damage potential, but work best when combined with other fighters, weapons, and ships to ensure they can deliver the damage.":
                "Les bombardiers ont un fort potentiel de dégâts, mais sont plus efficaces lorsqu'ils sont combinés avec d'autres chasseurs, armes et vaisseaux pour s'assurer qu'ils puissent infliger leurs dégâts.",
            
            # Divers
            "Percentage increases are additive. Percentage reductions are generally multiplicative.":
                "Les augmentations de pourcentage sont additives. Les réductions de pourcentage sont généralement multiplicatives.",
            
            "Slow-moving fleets do not attract storm strikes in hyperspace.":
                "Les flottes se déplaçant lentement n'attirent pas les tempêtes dans l'hyperespace.",
            
            # Interface utilisateur
            "When editing a text field, you can press Shift-Backspace to clear it, or Ctrl-Backspace to delete the last word.":
                "Lors de l'édition d'un champ de texte, vous pouvez appuyer sur Shift-Retour arrière pour l'effacer, ou Ctrl-Retour arrière pour supprimer le dernier mot.",
            
            "Most open-market trade is made unprofitable by tariffs. Exploit ongoing events and disruptions to make a profit.":
                "La plupart des échanges sur le marché libre sont rendus non rentables par les tarifs. Exploitez les événements en cours et les perturbations pour réaliser des profits.",
            
            "Hold Shift while adding or removing flux vents or capacitors to do it more quickly.":
                "Maintenez Shift enfoncé tout en ajoutant ou retirant des évents ou des condensateurs de flux pour le faire plus rapidement.",
            
            "Hold Shift while scrolling with the mousewheel to scroll more quickly.":
                "Maintenez Shift enfoncé tout en utilisant la molette de la souris pour défiler plus rapidement.",
            
            "Control-click to buy/sell a stack. Shift-click to pick up items one at a time. Hold Shift and click and drag to select a specific quantity.":
                "Ctrl-clic pour acheter/vendre un lot. Shift-clic pour prendre les objets un par un. Maintenez Shift et cliquez-glissez pour sélectionner une quantité spécifique.",
            
            "To pan the in-combat map, either right-click and drag or use the arrow keys.":
                "Pour faire défiler la carte pendant le combat, faites un clic droit et glissez ou utilisez les touches fléchées.",
            
            "Launching torpedoes at point-blank range can be hazardous to your ship.":
                "Lancer des torpilles à bout portant peut être dangereux pour votre vaisseau.",
            
            "Ships with a (D) designation are substandard versions of the normal hulls.":
                "Les vaisseaux avec une désignation (D) sont des versions inférieures des coques normales.",
            
            "Deploying ships in combat reduces their combat readiness (\"CR\"), which costs supplies to recover.":
                "Déployer des vaisseaux au combat réduit leur préparation au combat (« PC »), qui coûte des ressources à récupérer.",
            
            "You can create groups of ships using Ctrl and the number keys, and select them using the number keys. This works both in combat and in the deployment dialog.":
                "Vous pouvez créer des groupes de vaisseaux en utilisant Ctrl et les touches numériques, et les sélectionner avec les touches numériques. Cela fonctionne à la fois en combat et dans la fenêtre de déploiement.",
            
            "Carriers will stop launching replacement fighters once their combat readiness reaches 0%.":
                "Les transporteurs arrêteront de lancer des chasseurs de remplacement une fois que leur préparation au combat atteint 0 %.",
            
            "Carriers armed with only point-defense and missile weapons will attempt to keep away from enemy ships.":
                "Les transporteurs armés uniquement d'armes de défense ponctuelle et de missiles tenteront de se tenir à l'écart des vaisseaux ennemis.",
            
            "Ships consume supplies for maintenance based on their supplies/month stat, and consume extra supplies while recovering CR or undergoing repairs.":
                "Les vaisseaux consomment des ressources pour leur maintenance selon leur statistique de ressources/mois, et en consomment davantage lors de la récupération de PC ou des réparations.",
            
            "Your fleet can carry cargo, crew, or fuel in excess of its maximum capacity at the cost of extra supply consumption.":
                "Votre flotte peut transporter du cargo, de l'équipage ou du carburant au-delà de sa capacité maximale au prix d'une consommation supplémentaire de ressources.",
            
            "You can get extra info from many tooltips by pressing F1 to expand them.":
                "Vous pouvez obtenir des informations supplémentaires de nombreuses infobulles en appuyant sur F1 pour les développer.",
            
            "More guns isn't always better - having enough flux capacity and dissipation for sustained fire can be more important.":
                "Plus d'armes n'est pas toujours mieux - avoir assez de capacité et de dissipation de flux pour un tir soutenu peut être plus important.",
            
            "Refitting a ship in space will reduce its combat readiness, especially when changing hull mods.":
                "Réaménager un vaisseau dans l'espace réduira sa préparation au combat, particulièrement lors du changement de modifications de coque.",
            
            "Weapons that fire energy bolts or projectiles can hit targets beyond their maximum range, but only deal soft flux damage to shields when they do.":
                "Les armes qui tirent des projectiles énergétiques peuvent toucher des cibles au-delà de leur portée maximale, mais n'infligent que des dégâts de flux « mou » aux boucliers dans ce cas.",
            
            "You can create groups of ships using Ctrl and the number keys, and select them using the number keys. This works both in combat and in the deployment dialog.":
                "Vous pouvez créer des groupes de vaisseaux en utilisant Ctrl et les touches numériques, et les sélectionner avec les touches numériques. Cela fonctionne à la fois en combat et dans la fenêtre de déploiement.",
            
            "Carriers will stop launching replacement fighters once their combat readiness reaches 0%.":
                "Les transporteurs arrêteront de lancer des chasseurs de remplacement une fois que leur préparation au combat atteint 0 %.",
            
            "Carriers armed with only point-defense and missile weapons will attempt to keep away from enemy ships.":
                "Les transporteurs armés uniquement d'armes de défense ponctuelle et de missiles tenteront de se tenir à l'écart des vaisseaux ennemis.",
            
            "In combat, move the mouse around to pan the view.  Press 'T' to anchor your view to your target, and press 'T' again to go back to the normal view.":
                "En combat, déplacez la souris pour faire défiler la vue. Appuyez sur « T » pour verrouiller votre vue sur votre cible, et appuyez à nouveau sur « T » pour revenir à la vue normale.",
            
            "Press LMB to fire and RMB to use the shields.  Use WASD to pilot the ship.":
                "Appuyez sur le bouton gauche de la souris pour tirer et sur le bouton droit pour utiliser les boucliers. Utilisez ZQSD pour piloter le vaisseau.",
            
            "Firing weapons or using shields builds up flux.  When the flux level is maxed out, you'll have to wait for it to go down before you can fire again.":
                "Tirer avec les armes ou utiliser les boucliers accumule du flux. Lorsque le niveau de flux est au maximum, vous devrez attendre qu'il redescende avant de pouvoir tirer à nouveau.",
            
            "Ships consume supplies for maintenance based on their supplies/month stat, and consume extra supplies while recovering CR or undergoing repairs.":
                "Les vaisseaux consomment des ressources pour leur maintenance selon leur statistique de ressources/mois, et en consomment davantage lors de la récupération de PC ou des réparations.",
            
            "Your fleet can carry cargo, crew, or fuel in excess of its maximum capacity at the cost of extra supply consumption.":
                "Votre flotte peut transporter du cargo, de l'équipage ou du carburant au-delà de sa capacité maximale au prix d'une consommation supplémentaire de ressources.",
            
            "You can get extra info from many tooltips by pressing F1 to expand them.":
                "Vous pouvez obtenir des informations supplémentaires de nombreuses infobulles en appuyant sur F1 pour les développer.",
            
            "More guns isn't always better - having enough flux capacity and dissipation for sustained fire can be more important.":
                "Plus d'armes n'est pas toujours mieux - avoir assez de capacité et de dissipation de flux pour un tir soutenu peut être plus important.",
            
            "Refitting a ship in space will reduce its combat readiness, especially when changing hull mods.":
                "Réaménager un vaisseau dans l'espace réduira sa préparation au combat, particulièrement lors du changement de modifications de coque.",
            
            "Weapons that fire energy bolts or projectiles can hit targets beyond their maximum range, but only deal soft flux damage to shields when they do.":
                "Les armes qui tirent des projectiles énergétiques peuvent toucher des cibles au-delà de leur portée maximale, mais n'infligent que des dégâts de flux « mou » aux boucliers dans ce cas.",
            
            "You can create groups of ships using Ctrl and the number keys, and select them using the number keys. This works both in combat and in the deployment dialog.":
                "Vous pouvez créer des groupes de vaisseaux en utilisant Ctrl et les touches numériques, et les sélectionner avec les touches numériques. Cela fonctionne à la fois en combat et dans la fenêtre de déploiement.",
            
            "Carriers will stop launching replacement fighters once their combat readiness reaches 0%.":
                "Les transporteurs arrêteront de lancer des chasseurs de remplacement une fois que leur préparation au combat atteint 0 %.",
            
            "Carriers armed with only point-defense and missile weapons will attempt to keep away from enemy ships.":
                "Les transporteurs armés uniquement d'armes de défense ponctuelle et de missiles tenteront de se tenir à l'écart des vaisseaux ennemis.",
            
            "Deploying more ships than you need into combat can cost more supplies than you gain from fighting.":
                "Déployer plus de vaisseaux que nécessaire au combat peut coûter plus de ressources que vous n'en gagnez en combattant.",
            
            "Weapons have halved recoil when mounted in hardpoint slots.":
                "Les armes ont un recul réduit de moitié lorsqu'elles sont montées dans des emplacements de points d'ancrage.",
            
            "Scuttling a ship - or simply not recovering it - will produce more value in fuel and supplies than selling it would.":
                "Saborder un vaisseau - ou simplement ne pas le récupérer - produira plus de valeur en carburant et en ressources que sa vente.",
            
            "If a star system has few stable locations, you can create a new one by interacting with the star.":
                "Si un système stellaire a peu d'emplacements stables, vous pouvez en créer un nouveau en interagissant avec l'étoile.",
            
            "Assigning marines to attack a low-danger objective can create a diversion and reduce casualties from a dangerous raid more than keeping those marines in reserve.":
                "Assigner des marines à l'attaque d'un objectif peu dangereux peut créer une diversion et réduire les pertes d'un raid dangereux plus que de garder ces marines en réserve.",
            
            "The side with more capable officers in command of combat-ready ships gets more deployment points.":
                "Le camp avec les officiers les plus compétents aux commandes de vaisseaux prêts au combat obtient plus de points de déploiement.",
            
            "Ships with officers or s-mods are almost always recoverable if lost in combat. Some skills and hullmods can also make other ships always recoverable.":
                "Les vaisseaux avec des officiers ou des s-mods sont presque toujours récupérables s'ils sont perdus au combat. Certaines compétences et modifications de coque peuvent aussi rendre d'autres vaisseaux toujours récupérables.",
            
            "Scuttling or losing a ship with s-mods you've built into it grants enough bonus XP to gain back the story points spent on building the hullmods in.":
                "Saborder ou perdre un vaisseau avec des s-mods que vous y avez intégrés accorde assez d'XP bonus pour récupérer les points d'histoire dépensés pour intégrer ces modifications.",
            
            "Slipstreams are temporary and, in recent memory, synchronized with the standard Domain cycle. In the first half of the cycle, they tend to flow towards the galactic east, and in the second half, to the west.":
                "Les courants spatiaux sont temporaires et, dans la mémoire récente, synchronisés avec le cycle standard du Domaine. Dans la première moitié du cycle, ils tendent à s'écouler vers l'est galactique, et dans la seconde moitié, vers l'ouest.",
            
            "During a pursuit, you can deploy frigates from the flanks by clicking on them multiple times to cycle the deployment mode.":
                "Pendant une poursuite, vous pouvez déployer des frégates depuis les flancs en cliquant plusieurs fois dessus pour changer le mode de déploiement.",
            
            "Hullmods with a low ordnance point cost tend to have more powerful bonuses when built into the hull using a story point. More expensive hullmods tend to have penalties.":
                "Les modifications de coque avec un faible coût en points d'ordonnance ont tendance à avoir des bonus plus puissants lorsqu'elles sont intégrées à la coque avec un point d'histoire. Les modifications plus coûteuses ont tendance à avoir des pénalités."
        }
        
        # Application des traductions
        for i, tip in enumerate(data["tips"]):
            if isinstance(tip, dict):
                if "tip" in tip and tip["tip"] in translations:
                    tip["tip"] = fix_french_typography(translations[tip["tip"]])
            elif isinstance(tip, str) and tip in translations:
                data["tips"][i] = fix_french_typography(translations[tip])
        
        # Écriture du fichier traduit
        with open(output_file, 'w', encoding='utf-8', newline='\n') as f:
            json.dump(data, f, ensure_ascii=False, indent=4)
        
        print("Traduction terminée avec succès")
        return True
    except Exception as e:
        print(f"Erreur lors de la traduction : {e}")
        return False

if __name__ == "__main__":
    translate_tips()
