name: CI

on:
  push:
    branches: [ main, dev, feature/* ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest chardet
          
      - name: Check file encoding
        run: |
          python tools/check_encoding.py
          
      - name: Validate JSON files
        run: |
          python tools/validate_json.py
          
      - name: Validate CSV files
        run: |
          python tools/validate_csv.py
